const PREFIX = "REDUX_ROUTE_TRANSITION_ACTIONS_";
export const SHOW_CONFIRMATION_ACTION = PREFIX + "SHOW_CONFIRMATION_ACTION";
export const CONFIRM_LEAVE_ROUTE = PREFIX + "CONFIRM_LEAVE_ROUTE";
export const CONFIRM_STAY_ROUTE = PREFIX + "CONFIRM_STAY_ROUTE";
